spring:
  cloud:
    gateway:
      routes:
        - id: redisTest
          uri: http://localhost:8000
          predicates:
          - Path=/
          filters:
          - name: RequestRateLimiter
            args:
              key-resolver: "#{@userKeyResolver}"
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 2
